const all_data = [
	{
		name: 'roy',
		image_url: `https://fireemblemwiki.org/w/images/7/70/Portrait_roy_fe06.png`,
		supports: [
			{
				id: 0,
				friendship: 1,
				name: 'marcus',
				image_url: `https://fireemblemwiki.org/w/images/1/1c/Portrait_marcus_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				id: 1,
				friendship: 1,
				name: 'alen',
				image_url: `https://fireemblemwiki.org/w/images/7/73/Small_portrait_alen_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				id: 2,
				friendship: 1,
				name: 'lance',
				image_url: `https://fireemblemwiki.org/w/images/e/e9/Small_portrait_lance_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				id: 3,
				friendship: 1,
				name: 'wolt',
				image_url: `https://fireemblemwiki.org/w/images/2/2e/Small_portrait_wolt_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				id: 4,
				friendship: 1,
				name: 'shanna',
				image_url: `https://fireemblemwiki.org/w/images/0/07/Small_portrait_shanna_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				id: 5,
				friendship: 1,
				name: 'sue',
				image_url: `https://fireemblemwiki.org/w/images/e/e7/Small_portrait_sue_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				id: 6,
				friendship: 1,
				name: 'lilana',
				image_url: `https://fireemblemwiki.org/w/images/5/5c/Small_portrait_lilina_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				id: 7,
				friendship: 1,
				name: 'larum',
				image_url: `https://fireemblemwiki.org/w/images/b/bc/Small_portrait_larum_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				id: 8,
				friendship: 1,
				name: 'ceceila',
				image_url: `https://fireemblemwiki.org/w/images/a/a3/Small_portrait_cecilia_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				id: 9,
				friendship: 1,
				name: 'sophia',
				image_url: `https://fireemblemwiki.org/w/images/8/89/Small_portrait_sophia_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
		],
	},
	{
		name: 'marcus',
		image_url: `https://fireemblemwiki.org/w/images/1/1c/Portrait_marcus_fe06.png`,
		supports: [
			{
				name: 'roy',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/6/65/Small_portrait_roy_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				name: 'alen',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/7/73/Small_portrait_alen_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				name: 'lance',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/e/e9/Small_portrait_lance_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				name: 'wolt',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/2/2e/Small_portrait_wolt_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				name: 'lilina',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/5/5c/Small_portrait_lilina_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
		],
	},
	{
		name: 'alen',
		image_url: `https://fireemblemwiki.org/w/images/b/b0/Portrait_alen_fe06.png`,
		supports: [
			{
				name: 'roy',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/6/65/Small_portrait_roy_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				name: 'marcus',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/9/92/Small_portrait_marcus_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				name: 'lance',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/e/e9/Small_portrait_lance_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				name: 'wolt',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/2/2e/Small_portrait_wolt_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				name: 'wade',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/6/6b/Small_portrait_wade_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				name: 'thea',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/2/27/Small_portrait_thea_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
		],
	},
	{
		name: 'lance',
		image_url: `https://fireemblemwiki.org/w/images/a/ae/Portrait_lance_fe06.png`,
		supports: [
			{
				name: 'roy',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/6/65/Small_portrait_roy_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				name: 'marcus',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/9/92/Small_portrait_marcus_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				name: 'alen',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/7/73/Small_portrait_alen_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				name: 'wolt',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/2/2e/Small_portrait_wolt_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				name: 'wade',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/6/6b/Small_portrait_wade_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				name: 'thea',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/2/27/Small_portrait_thea_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
		],
	},
	{
		name: 'wolt',
		image_url: `https://fireemblemwiki.org/w/images/2/29/Portrait_wolt_fe06.png`,
		supports: [
			{
				name: 'roy',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/6/65/Small_portrait_roy_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				name: 'marcus',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/9/92/Small_portrait_marcus_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				name: 'alen',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/7/73/Small_portrait_alen_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				name: 'lance',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/e/e9/Small_portrait_lance_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				name: 'sue',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/e/e7/Small_portrait_sue_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
		],
	},
	{
		name: 'bors',
		image_url: `https://fireemblemwiki.org/w/images/9/96/Portrait_bors_fe06.png`,
		supports: [
			{
				name: 'astore',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/6/65/Small_portrait_roy_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				name: 'marcus',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/9/92/Small_portrait_marcus_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				name: 'alen',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/7/73/Small_portrait_alen_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				name: 'lance',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/e/e9/Small_portrait_lance_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
			{
				name: 'sue',
				friendship: 1,
				image_url: `https://fireemblemwiki.org/w/images/e/e7/Small_portrait_sue_fe06.png`,
				c: '',
				b: '',
				a: '',
			},
		],
	},
];

export default all_data;
